# Generated by Django 5.2 on 2025-04-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='equipment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='max_teams',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='results_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='required_qualifications',
            field=models.ManyToManyField(to='events.qualification'),
        ),
    ]
