# Generated by Django 5.2 on 2025-04-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_qualification_event_equipment_event_max_teams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(default=0, verbose_name='Максимальное количество участников'),
        ),
        migrations.AlterField(
            model_name='participationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('approved', 'Одобрение'), ('rejected', 'Отклонение')], default='pending', max_length=10),
        ),
    ]
