# Generated by Django 5.2 on 2025-04-06 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_max_participants_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date'], 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='participationrequest',
            options={'verbose_name': 'Заявка на участие', 'verbose_name_plural': 'Заявки на участие'},
        ),
        migrations.AlterModelOptions(
            name='qualification',
            options={'verbose_name': 'Квалификация', 'verbose_name_plural': 'Квалификации'},
        ),
        migrations.AlterModelOptions(
            name='sporttype',
            options={'verbose_name': 'Вид спорта', 'verbose_name_plural': 'Виды спорта'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='required_qualifications',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(verbose_name='Дата и время проведения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='equipment',
            field=models.TextField(blank=True, verbose_name='Необходимое оборудование'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(default=0, help_text='0 означает без ограничений', verbose_name='Максимальное количество участников'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_teams',
            field=models.PositiveIntegerField(default=0, verbose_name='Максимальное количество команд'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='Организатор'),
        ),
        migrations.AlterField(
            model_name='event',
            name='results_published',
            field=models.BooleanField(default=False, verbose_name='Результаты опубликованы'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sport_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.sporttype', verbose_name='Вид спорта'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название мероприятия'),
        ),
        migrations.AlterField(
            model_name='participationrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='participationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='pending', max_length=10, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='participationrequest',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.team', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='participationrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название квалификации'),
        ),
        migrations.AlterField(
            model_name='sporttype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название вида спорта'),
        ),
        migrations.AlterField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captained_teams', to=settings.AUTH_USER_MODEL, verbose_name='Капитан'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название команды'),
        ),
        migrations.AlterField(
            model_name='team',
            name='required_players',
            field=models.PositiveIntegerField(help_text='Минимальное количество игроков в команде', verbose_name='Требуемое количество участников'),
        ),
        migrations.AlterField(
            model_name='team',
            name='sport_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.sporttype', verbose_name='Вид спорта'),
        ),
    ]
